name: Xcode - Build

on: 
  - workflow_dispatch

jobs:
  build:
    name: Build using xcodebuild command
    runs-on: macos-latest
    env:
      #scheme: YggdrasilNetwork
      scheme: default
      archive_path: archive
    outputs:
      scheme: ${{ steps.scheme.outputs.scheme }}
      archive_path: ${{ env.archive_path }}
      artifact: ${{ env.scheme }}.ipa
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Scheme
        id: scheme
        run: |
          if [ $scheme = default ]
          then
            scheme_list=$(xcodebuild -list -json | tr -d "\n")
            scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
            echo Using default scheme: $scheme
          else
            echo Using configured scheme: $scheme
          fi
          echo "scheme=$scheme" >> $GITHUB_OUTPUT
      - name: Set filetype_parameter
        id: filetype_parameter
        run: |
          filetype_parameter=`ls -A | grep -i \\.xcworkspace\$ && echo workspace || echo project`
          echo "filetype_parameter=$filetype_parameter" >> $GITHUB_OUTPUT
      - name: Set file_to_build
        id: file_to_build
        run: |
          file_to_build=`ls -A | grep -i \\.xcworkspace\$ || ls -A | grep -i \\.xcodeproj\$`
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          echo "file_to_build=$file_to_build" >> $GITHUB_OUTPUT
      - name: Checkout yggdrasil-go
        uses: actions/checkout@v3
        with:
          repository: 'yggdrasil-network/yggdrasil-go'
          ref: 'master'
          path: 'yggdrasil-go'
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Install gomobile & Add Path
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          echo $(go env GOPATH)/bin >> $GITHUB_PATH
          gomobile init
      - name: Build Yggdrasil.xcframework
        run: |
          cd yggdrasil-go
          contrib/mobile/build -i
          mv Yggdrasil.xcframework ..
      - name: Archive
        env:
          scheme: ${{ steps.scheme.outputs.scheme }}
          filetype_parameter: ${{ steps.filetype_parameter.outputs.filetype_parameter }}
          file_to_build: ${{ steps.file_to_build.outputs.file_to_build }}
        #run: xcodebuild archive -archivePath "$archive_path" -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -sdk iphoneos -arch arm64 -configuration Release | xcpretty && exit ${PIPESTATUS[0]}
        run: xcodebuild archive -archivePath "$archive_path" -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -sdk iphoneos -arch arm64 -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        #run: xcodebuild build -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -sdk iphoneos -arch arm64 -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      #- name: Print Folder Tree
      #  uses: jaywcjlove/github-action-folder-tree@main
      - name: Tar Build Artifact
        run: tar -cvf "$archive_path.xcarchive.tar" "$archive_path.xcarchive"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.archive_path }}.xcarchive.tar
          path: ${{ env.archive_path }}.xcarchive.tar
      - name: Create IPA
        run: |
          mv "$archive_path.xcarchive/Products/Applications" Payload
          zip -r "$scheme.ipa" "Payload" -x "._*" -x ".DS_Store" -x "__MACOSX"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.scheme }}.ipa
          path: ${{ env.scheme }}.ipa
